version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "stats-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      ports:
        "5432:5432"

  ewm-service:
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "ewm-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      ports:
        "5442:5442"
