CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR,
    uri       VARCHAR,
    ip        VARCHAR,
    timestamp TIMESTAMP,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);