CREATE TABLE IF NOT EXISTS statistics
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255),
    uri       VARCHAR(511),
    ip        VARCHAR(15),
    timestamp TIMESTAMP,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);